// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnasdyvakwsvngajpuds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuYXNkeXZha3dzdm5nYWpwdWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTIyNTEsImV4cCI6MjA3MDY2ODI1MX0.cY9FA3vTQj7aOc4RBenTCHqAwM7-X98D4onxWoYDI9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});